# Generated by Django 2.2.12 on 2020-06-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Please fill in', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='Please fill in', max_length=200),
        ),
    ]
