# Generated by Django 2.2.12 on 2020-06-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200616_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncatagorized', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(default='uncatagorized', max_length=200),
        ),
    ]
