# Generated by Django 2.2.12 on 2020-06-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200616_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(default='uncategorized', max_length=200),
        ),
    ]
