# Generated by Django 2.2.12 on 2020-06-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='location',
        ),
    ]
